services:
  server:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 3000:3000

  frontend:
    build:
      context: ./app
    ports:
      - 4200:4200

  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - ./data:/data/db
      - config:/data/configdb
      - log:/var/log/mongodb

volumes:
  config:
  log:
